name: Build test
permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main

jobs:
  build-fdk-harvest-admin-service:
    name: Build when pull request is created
    if: ${{ github.actor != 'dependabot[bot]' &&  github.event.pull_request.draft == false }}
    uses: Informasjonsforvaltning/workflows/.github/workflows/build-push.yaml@main
    with:
      app_name: fdk-harvest-admin-service
      environment: test
      java_version: '21'
      coverage_file_path: ./target/site/jacoco/jacoco.xml
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}